### ISSUE TITLE
Script assumes the image matches board arch.

### ISSUE THREAD

**Issue by gawainXX** [libre-computer-project/libretech-raspbian-portability#5]
This script corrupted an image which I did not notice until afterwards when apt upgrades began to go sideways.
I originally had an RPI 3B+ running Raspbian 11 Buster, (32-Bit) as it's the recommended flavor. However appearantly even though the conversion seemed to work, I later found out that it installed 64-bit kernel components onto my 32-bit Image, which has lead to some major apt update issues amount other inconsistencies.

Please change the logic for the deb and kernel packages to use armhf if the distro is using that, right now it appears to be hardcoded to use the the board architecture arch=${BOARD_arch} 

I'm having to rebuild a system as a result of this.

This was also causing confusion for many packages as the kernel is and reports it's aarch64, however the system is incapable of running aarch64 binaries.

**Comment by dsx724** [comment]
BOARD_arch is set to the architecture of the target board you want to run the image on. If the target board is 64-bit, it will install 64-bit components onto the 32-bit userland. This is correct.

>I'm having to rebuild a system as a result of this.
Per the documentation, backup the image before running this.

>This was also causing confusion for many packages as the kernel is and reports it's aarch64, however the system is incapable of running aarch64 binaries.
This is only an issue if the software does not distinguish between Debian's different host flags `dpkg-architecture`. This is a problem with the arch detection of those software(s).
