### ISSUE TITLE
ROC-RK3328-CC and 2022-09-22-raspios-buster-armhf.img

### ISSUE THREAD

**Issue by jng3555** [libre-computer-project/libretech-raspbian-portability#6]
Anybody manages to get it working for 2022-09-22-raspios-buster-armhf.img?
(https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-09-26/2022-09-22-raspios-buster-armhf.img.xz)

The moment power is on, the red LED is on. The yellow/green blinks once or twice and is off. I saw the keyboard initiated. There is no video out.

The board, Rk3328-CC is good. I tested with Armbian Jammy.
Note: 2022-09-22-raspios-buster-armhf.img works on Raspberry Pi. It was "sudo apt update && sudo apt upgrade".

**Comment by dsx724** [comment]
ROC-RK3328-CC bootloader had issues and those issues have been resolved in July. Please try again now and re-open this issue if the portability script does not work now.
