### ISSUE TITLE
shim missing

### ISSUE THREAD

**Issue by herrin** [libre-computer-project/libretech-raspbian-portability#7]
oneshot.sh puts a hold on the shim-signed package, but neither shim-signed nor shim-unsigned are generally installed on the Raspberry Pi source machine. These critical packages must exist or oneshot.sh will produce an unbootable image. The readme contains no relevant instructions.

In addition, shim-signed 15.7 (the current version acquired with apt-get install shim-signed) does not successfully boot on Le Potato. The older version 15.4 present in Libre's special version of Raspbian for Le Potato works.

**Comment by dsx724** [comment]
Can you provide the full logs with `bash -x oneshot.sh BOARD` from the Raspbian image in question? This script is CI'ed through the latest Raspbian image. The shim-signed is only used for secure boot and is not a mandatory package for grub-efi-arm or grub-efi-arm64. We had other reports of it causing failures but we don't have the relevant information to debug. The latest shim-signed from Debian is broken with the recent update which is why we added the block.

**Comment by herrin** [comment]
[oneshot-output.txt](https://github.com/libre-computer-project/libretech-raspbian-portability/files/11582577/oneshot-output.txt)
The script fails at:
 cp /boot/EFI/raspbian/grub.cfg /boot/EFI/debian/grub.cfg

because /boot/EFI/raspian does not exist. This prevents the bootloader from being installed at all.

To try to compensate, run the remaining elements of the script by hand:

```
                BOARD_name=aml-s905x-cc
                BOARD_bootSector=1
                BOARD_console=AML0
                BOARD_bootLoader=1
                BOARD_arch=arm64
                BOARD_arch_cpu=arm64
                BOARD_cpu=aarch64
target_part=$(findmnt -no SOURCE /)
target_disk=$(lsblk --list -no type,name --inverse "$target_part" | grep ^disk | cut -d " " -f 2)
        BOOT_LOADER_URL="http://boot.libre.computer/ci/$BOARD_name"
        boot_loader_file=$(mktemp)
        wget -O "$boot_loader_file" "$BOOT_LOADER_URL"
        dd if="$boot_loader_file" of=/dev/"$target_disk" bs=512 seek=$BOARD_bootSector
        
1664+0 records in
1664+0 records out
851968 bytes (852 kB, 832 KiB) copied, 0.253068 s, 3.4 MB/s
```

And actually, this time through, that worked, so I must have done something else the first time around.

So, narrow the bug report to: The script fails at:
 cp /boot/EFI/raspbian/grub.cfg /boot/EFI/debian/grub.cfg

**Comment by dsx724** [comment]
We can patch that. In the mean time, can you please provide the source of the images you are using? We need to replicate it on our end to make sure no other issues exist. However, the fact that your /boot/EFI/raspbian/grub.cfg does not exist is strange as grub-install will use the distribution in /etc/os-release to generate the folder name for /boot/EFI/{distro}. So something is not standard and we would like to figure out why.

**Comment by dsx724** [comment]
@herrin This should be fixed with the latest commit. Please let us know if it fixes it for you.

**Comment by herrin** [comment]
I no longer recall the original source (I've been running the image on a Raspberry Pi for some time) but it would have been one of the arm64 images from either https://www.raspberrypi.com/software/operating-systems/ or https://raspi.debian.net/tested-images/. If it helps, this is the contents of /etc/os-release:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by herrin** [comment]
Tried the latest commit and it worked.
