### ISSUE TITLE
Proc does not handle porting from USB's

### ISSUE THREAD

**Issue by kn2tod** [libre-computer-project/libretech-raspbian-portability#8]
The procedure assumes the source disk is MMCBLK* and thereby postfixes "p1" to the source disk's name and subsequently can't find the start of the disk.  USB disks are usually defined as "sda" and thus the proc can't find "sdap1" - instead, should be looking for "sda1".

**Comment by dsx724** [comment]
non-mmc boot is not supported.

**Comment by kn2tod** [comment]
First, one may be building an image on a non-mmc device before porting/cloning it to an mmc device.  Secondly, the product supports booting from non-mmc devices.  So the logic of your process forces me to work solely with mmc devices for porting?
It can't even handle the situation where the mmc is plugged in via an adapter that registers as non-mmc?

**Comment by dsx724** [comment]
It is designed to run on the active system. It does not target a non-running system.

**Comment by kn2tod** [comment]
Wow!  The active system is running on a USB!  But we can't target another system, regardless of whether its a USB or MMC based system, unless the source system, the active system, is running on an MMC?!?  

The purpose of your procedure is to prep a system to run on another system on which it currently does not run, but because of a shortcoming in that procedure, one has to downgrade the active system to a lesser device because a change in the procedure can not be made to generalize it for all devices.

A one character change in the script gets it to work on an active USB system (but breaks it for MMC systems). Adding another couple of characters, ok, another line or two, can make it work for both.

**Comment by dsx724** [comment]
1) This script only ports the active system. Not another system.
2) This script specifically states it only accounts for a certain setup.
3) The script is open source. Feel free to write your own targeting code. We even take pull requests if the code has no regressions on the supported setup.

**Comment by dsx724** [comment]
Raspbian images for Libre Computer boards are available here: https://hub.libre.computer/t/raspbian-11-bullseye-for-libre-computer-boards/82

This script's sole purpose is to port active systems and we do not have the bandwidth to expand the scope. You are free to fork for your needs. Feel free to submit a pull request for changes. Closing this for now.
